### ISSUE TITLE
Consider switching to `em` unit

### ISSUE THREAD

**Issue by adamschwartz** [saeedalipoor/icono#16]
Awesome work!

After looking at the way you handled [icon sizes](https://github.com/saeedalipoor/icono/blob/73c4c5fd78c2a24708988d8baccfe19bc5f8619c/less/variables.less#L2) (which I thought was really clever, btw), I couldn’t help but wonder if you might benefit from employing same strategy but with fractional `em`s instead. (So setting a base font-size of say `16px` or `32px` and then setting `@1 = .0625em`,`@2 = .125em`, etc.)

The potential benefit of this is you could then have a `.icono-2x` class, for example, which would simply apply `font-size: 64px` and all of the icons would adjust.

I have made some icons like this before and have run into odd browser rounding issues. So maybe this is the same thing you encountered. But I think it might be fine if you set a base font size for all icons in `px` and then use `em` for the `width`, `height`, `border-width`, `::after` and `::before` sizes, etc.

I’d be happy to take a stab at PR if you think this is something icono could benefit from.

**Comment by joaocunha** [comment]
+1.

A single class approach also works for that:

```css
.top-menu [class^="icono-"] {
    font-size: 16px;
}

.sidebar [class^="icono-"] {
    font-size: 24px;
}
```

Not to mention media queries.

**Comment by adamschwartz** [comment]
@joaocunha Good points. Only thing I’d just caveat is that doing non-integer multiples of the base font size (whatever that ends up as in this `em` world), could produce non-pixel-fitted icons or other undesirable results due to rounding. So once a base font size is set at say `16px` or `32px`, you’ll want to only user integer multiples of such size.

This made me just think of a potentially interesting approach in which the base font size is set to `1px`, and so you have em units like `1em`, `2em`, etc. essentially behaving as pixels. Then `2px`, `3x`, base font size would be your multiples. This may have strange consequences for icons inline with commonly sized text, though. I may take a crack at it though just for fun.

**Comment by joaocunha** [comment]
@adamschwartz I don't think non-integer would cause any side effects as long as we're using `em`s. As a matter of fact, even non-integer pixels may round very nicely, [as you can see on vUnit](http://joaocunha.github.io/vunit/).

The easiest way to convert is to use `font-size:10px` as a base, and convert the units to `em`.

FROM:
```css
.icono-check {
    width: 28px;
    height: 28px;
    margin: 3px 0 3px 6px;
    transform: rotate(-45deg);
}
```

TO:
```css
/* base value for all icons, comes as standard and can be overriden by cascade */
[class^="icono-"] {
    font-size: 10px;
}

.icono-check {
    width: 2.8em;
    height: 2.8em;
    margin: .3em 0 .3em .6em;
    transform: rotate(-45deg);
}
```
