### ISSUE TITLE
Icon sizes

### ISSUE THREAD

**Issue by anaibol** [saeedalipoor/icono#34]
I was asking me how would I resize an icon, for an small button for example. Would that be possible with a class "small" for example or without modifying the variables?
Thanks for sharing this :D

**Comment by jgoodall** [comment]
is there any way to adjust size using css?

**Comment by jaywcjlove** [comment]
@jgoodall @anaibol using transform's `scale`,  Size the effect you want.

```css
[class*=icono-] {
    transform: scale(0.6,0.6);
}
```
